# Generated by Django 4.1.2 on 2022-10-08 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='id_historico',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='id_voo',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='historicoPartidaReal',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='aeroportoDestino',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='aeroportoOrigem',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='rota',
        ),
        migrations.AddField(
            model_name='historico',
            name='horarioPartidaReal',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='historico',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historico',
            name='voo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.voo'),
        ),
        migrations.AddField(
            model_name='voo',
            name='destino',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='voo',
            name='origem',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='horarioChegadaReal',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='voo',
            name='codigoVoo',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='voo',
            name='horarioChegadaProgramado',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='voo',
            name='horarioPartidaProgramado',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='relacao',
        ),
    ]
