# Generated by Django 4.1.2 on 2022-11-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_historico_id_alter_voo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='voo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.voo'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='companhia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voo',
            name='destino',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voo',
            name='origem',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
