# Generated by Django 4.1.2 on 2022-11-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_historico_voo_alter_voo_companhia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='horarioChegadaReal',
            new_name='horarioReal',
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='horarioChegadaProgramado',
            new_name='horarioProgramado',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='horarioPartidaReal',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='horarioPartidaProgramado',
        ),
        migrations.AlterField(
            model_name='historico',
            name='status',
            field=models.CharField(choices=[('EMBARCANDO', 'Embarcando'), ('CANCELADO', 'Cancelado'), ('PROGRAMADO', 'Programado'), ('TAXIANDO', 'Taxiando'), ('PRONTO', 'Pronto'), ('AUTORIZADO', 'Autorizado'), ('EM_VOO', 'Em Voo'), ('ATERRISSADO', 'Aterrissado')], max_length=30, null=True),
        ),
    ]
